/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiSetup: typeof import('./src/components/firstRun/AiSetup.vue')['default']
    AppActionButton: typeof import('./src/components/ui/AppActionButton.vue')['default']
    AppButton: typeof import('./src/components/ui/AppButton.vue')['default']
    AppCard: typeof import('./src/components/ui/AppCard.vue')['default']
    AppChip: typeof import('./src/components/ui/AppChip.vue')['default']
    AppConfirm: typeof import('./src/components/ui/AppConfirm.vue')['default']
    AppDangerZone: typeof import('./src/components/ui/AppDangerZone.vue')['default']
    AppEmpty: typeof import('./src/components/ui/AppEmpty.vue')['default']
    AppField: typeof import('./src/components/ui/AppField.vue')['default']
    AppModal: typeof import('./src/components/ui/AppModal.vue')['default']
    AppSegmented: typeof import('./src/components/ui/AppSegmented.vue')['default']
    AppSkeleton: typeof import('./src/components/ui/AppSkeleton.vue')['default']
    AppStatTile: typeof import('./src/components/ui/AppStatTile.vue')['default']
    AppSwitch: typeof import('./src/components/ui/AppSwitch.vue')['default']
    AppSwitchRow: typeof import('./src/components/ui/AppSwitchRow.vue')['default']
    AutomationTaskCard: typeof import('./src/components/automation/AutomationTaskCard.vue')['default']
    ChatMessageBubble: typeof import('./src/components/chat/ChatMessageBubble.vue')['default']
    ChatView: typeof import('./src/components/ChatView.vue')['default']
    FeedbackHost: typeof import('./src/components/ui/FeedbackHost.vue')['default']
    HomePanel: typeof import('./src/components/home/HomePanel.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    LanguageSelect: typeof import('./src/components/firstRun/LanguageSelect.vue')['default']
    ModelSelect: typeof import('./src/components/firstRun/ModelSelect.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    OperationDrawer: typeof import('./src/components/automation/OperationDrawer.vue')['default']
    PluginWidgets: typeof import('./src/components/chat/PluginWidgets.vue')['default']
    Ready: typeof import('./src/components/firstRun/Ready.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    Welcome: typeof import('./src/components/firstRun/Welcome.vue')['default']
  }
}
