// <auto-generated />
// 来源：src/assets/style/tokens.ts；请使用 pnpm theme:sync 同步。
using Avalonia.Media;
using Avalonia.Media.Immutable;

namespace Nori.Desktop.Appearance;

/// <summary>原生深色主题令牌；静态画刷没有 UI 线程所有权。</summary>
internal static class NoriThemeTokens
{
	private static readonly IReadOnlyDictionary<string, string> Values = new Dictionary<string, string>
	{
		["nori-teal"] = "#77C6D4",
		["nori-teal-bright"] = "#9ED2D2",
		["nori-teal-soft"] = "#B6D5D9",
		["bg-base"] = "#161A22",
		["bg-abyss"] = "#13171E",
		["bg-deep"] = "#1B2029",
		["bg-panel"] = "#272E39",
		["bg-card"] = "#EB1E232D",
		["bg-card-hover"] = "#F0272E39",
		["bg-card-active"] = "#F52D3741",
		["bg-glass"] = "#DB161A22",
		["bg-glass-modal"] = "#F5161A22",
		["bg-sidebar"] = "#8C13171E",
		["bg-input"] = "#252C36",
		["bg-selection"] = "#293E46",
		["text-primary"] = "#E8EFEF",
		["text-body"] = "#CEDBDC",
		["text-muted"] = "#A7B9BF",
		["text-faint"] = "#95A9B1",
		["line-subtle"] = "#299ED2D2",
		["line-strong"] = "#4D9ED2D2",
		["line-glow"] = "#739ED2D2",
		["success"] = "#80C9AA",
		["warning"] = "#F1B24A",
		["danger"] = "#FB3C44",
		["danger-text"] = "#FF7D84",
		["glow-teal"] = "#339ED2D2",
		["glow-teal-soft"] = "#149ED2D2",
		["glow-teal-strong"] = "#4D9ED2D2",
		["on-teal"] = "#16232B",
		["text-placeholder"] = "#95A9B1",
		["text-disabled"] = "#798F99",
		["nori-teal-pressed"] = "#64B1C0",
		["info-hover"] = "#B6DFE1",
		["info-pressed"] = "#6AAFBC",
		["overlay-2"] = "#05FFFFFF",
		["overlay-4"] = "#0AFFFFFF",
		["overlay-6"] = "#0FFFFFFF",
		["overlay-8"] = "#14FFFFFF",
		["overlay-12"] = "#1FFFFFFF",
		["overlay-20"] = "#33FFFFFF",
		["bg-popover"] = "#FA1E232D",
		["bg-menu"] = "#FA161A22",
		["bg-tooltip"] = "#FA1E232D",
		["scrim"] = "#A603060C",
		["slider-fill"] = "#77C6D4",
		["slider-fill-hover"] = "#9ED2D2",
		["window-focus-border"] = "#9ED2D2",
		["window-focus-glow"] = "#249ED2D2",
		["chat-user-bg"] = "#3D3D47",
		["chat-user-bg-end"] = "#4A4A55",
		["chat-user-text"] = "#E8E8EC",
		["chat-ai-bg"] = "#D2E8E9",
		["chat-ai-bg-end"] = "#CAF5F1",
		["chat-ai-text"] = "#45454F",
		["chat-ai-border"] = "#70FEFEFE",
		["chat-composer"] = "#56565F",
		["chat-white"] = "#FEFEFE",
		["chat-focus-placeholder"] = "#32616D",
		["chat-approval-danger"] = "#B01521",
		["chat-markdown-link"] = "#0369A1",
		["chat-markdown-quote"] = "#4A7C82",
		["traffic-close"] = "#FF5F56",
		["traffic-close-hover"] = "#E0443E",
		["traffic-minimize"] = "#FFBD2E",
		["traffic-minimize-hover"] = "#DEA123",
		["traffic-zoom"] = "#27C93F",
		["traffic-zoom-hover"] = "#1AAB29",
	};
	private static readonly IReadOnlyDictionary<string, IBrush> Brushes = Values.ToDictionary(
		pair => pair.Key, pair => (IBrush)new ImmutableSolidColorBrush(Avalonia.Media.Color.Parse(pair.Value)));
	private static readonly IReadOnlyDictionary<string, double> Measures = new Dictionary<string, double>
	{
		["radius-xs"] = 4,
		["radius-sm"] = 8,
		["radius-md"] = 12,
		["radius-lg"] = 16,
		["radius-pill"] = 999,
		["spacing-0"] = 0,
		["spacing-1"] = 4,
		["spacing-2"] = 8,
		["spacing-3"] = 12,
		["spacing-4"] = 16,
		["spacing-5"] = 20,
		["spacing-6"] = 24,
		["spacing-7"] = 28,
		["spacing-8"] = 32,
		["spacing-9"] = 36,
		["spacing-10"] = 40,
		["spacing-12"] = 48,
		["spacing-14"] = 56,
		["spacing-16"] = 64,
		["spacing-20"] = 80,
		["spacing-0.5"] = 2,
		["spacing-1.5"] = 6,
		["spacing-2.5"] = 10,
		["spacing-3.5"] = 14,
		["font-xs"] = 12,
		["font-sm"] = 12,
		["font-base"] = 13,
		["font-md"] = 14,
		["font-lg"] = 16,
		["font-xl"] = 18,
		["font-2xl"] = 22,
		["font-3xl"] = 26,
	};

	internal static string Value(string name) => Values[name];
	internal static Color Color(string name) => Avalonia.Media.Color.Parse(Value(name));
	internal static IBrush Brush(string name) => Brushes[name];
	internal static double Measure(string name) => Measures[name];
}
